CREATE table hoteles( 
        IdHotel INTEGER PRIMARY KEY AUTOINCREMENT
      , NombreFantasia TEXT NOT NULL UNIQUE
      , Habitaciones INTEGER NOT NULL
      );
	
INSERT INTO hoteles (NombreFantasia, Habitaciones)
VALUES 
    ('THE RITZ LONDON', 300),
    ('WALDORF ASTORIA NEW YORK', 1500),
    ('BURJ AL ARAB', 202),
    ('HOTEL DU CAP-EDEN-ROC', 118),
    ('BELMOND COPACABANA PALACE', 239),
    ('HOTEL PLAZA ATHENEE', 208),
    ('THE PENINSULA HONG KONG', 300),
    ('THE SAVOY', 268),
    ('MANDARIN ORIENTAL BANGKOK', 393),
    ('HOTEL DE PARIS MONTE-CARLO', 207),
    ('ATLANTIS THE PALM', 1539),
    ('THE SHANGRI-LA HOTEL, PARIS', 101),
    ('PALMS CASINO RESORT', 703),
    ('THE LANGHAM, LONDON', 380),
    ('MARINA BAY SANDS', 2561),
    ('HOTEL DEL CORONADO', 757),
    ('THE PLAZA HOTEL', 282),
    ('BURJ KHALIFA', 196),
    ('LE MEURICE', 160),
    ('MANDARIN ORIENTAL, NEW YORK', 244),
    ('THE DORCHESTER', 250),
    ('FAIRMONT LE CHATEAU FRONTENAC', 611),
    ('HOTEL HASSLER ROMA', 87),
    ('THE WESTIN PALACE MADRID', 470),
    ('THE BEVERLY HILLS HOTEL', 208),
    ('HOTEL NATIONAL MOSCOW', 202),
    ('THE ROYAL CRESCENT HOTEL & SPA', 45),
    ('HOTEL ALFONSO XIII', 151),
    ('THE RITZ-CARLTON, TOKYO', 245),
    ('PALACE HOTEL TOKYO', 278);
